version: "3.9"
services:

  fluentd:
    container_name: fluentd
    image: "${USER}/fluentd:v1.13"
    ports:
      - "24224:24224"
      - "24231:24231"
    volumes:
      - "./config/fluentd:/fluentd/etc"

  logs-apache:
    container_name: logs-apache
    depends_on: 
      - fluentd
    entrypoint: ["/scripts/apache-logs.sh"]
    logging:
      driver: "fluentd"
      options:
        tag: docker.apache
    image: alpine:3.13.5
    volumes:
      - ./config/logger:/scripts
  

networks:
  default:
    name: logging
    driver: bridge
    ipam:
     config:
       - subnet: 172.20.0.0/24
         gateway: 172.20.0.1
